version: '2'

services:
    db:
        image: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./.data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    phpfpm:
        build: ./docker/phpfpm
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs

    nginx:
        build: ./docker/nginx
        ports:
            - 80:80
        volumes_from:
            - phpfpm
        volumes:
            - ./logs/nginx/:/var/log/nginx

    elk:
        image: willdurand/elk
        ports:
            - 81:80
        volumes:
            - ./docker/elk/logstash:/etc/logstash
            - ./docker/elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - phpfpm
            - nginx